name: Maine Guard Safe
favicon: null
layout_spectrum: 0.5080149869900197
typography_spectrum: 0.8959364842157811
title: Maine GuardSafe Professional Security
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.5629600528627634
  lightness: 0.17702186992391944
  saturation: 0.7924882918596268
  rhythmicContrast: 0.044952471973374486
purpose: []
